### ISSUE TITLE
PhantomJS version bump

### ISSUE THREAD

**Issue by devasur** [cjpetrus/url2img#1]
I have tested it with phantomjs-prebuilt 2.1.4.  Works fine.  IMO it will be a good idea to bump the version.  Unless there is something that I am missing.

**Comment by devasur** [comment]
Glad to see that your version is much more stable under heavily parallel scenarios.  Currently in action on our production @ https://walkinto.in .  Using it to create thumbnails for social media sharing previews.

**Comment by cjpetrus** [comment]
@devasur Glad to hear it, what kind of stack are you running? I'm currently migrating alot of this stuff to a server-less architecture.

**Comment by devasur** [comment]
Currently this is invoked inline from a node cluster.  In front of it there is an NGINX doing reverse proxying.  I was extremely skeptical about the stability of that design and am still considering moving it out of the main thread.  But so far, your careful handling of childProcess is proving very stable.  Around here we don't write extra code.  So will wait and see ;)
