### ISSUE TITLE
Sometimes it works, sometimes it doesn't.

### ISSUE THREAD

**Issue by StefanSchwartze** [cjpetrus/url2img#5]
This module very often creates errors on some urls. My domain "http://stefanschwartze.com" I get almost never to work, maybe in 1 of 10 cases or less. This also occurs on other websites. I've also seen that sometimes it resolves the promise without saving the image.
I used the default settings from your Readme..

**Comment by cjpetrus** [comment]
@StefanSchwartze I'm sure the problem is easily debugged on your end. It works 10/10 times with random websites including yours for me on a fresh osx machine. if you want to post more information and actually put some effort into your issue, I'll help you further.
