### ISSUE TITLE
Let's join our forces

### ISSUE THREAD

**Issue by kimmobrunfeldt** [cjpetrus/url2img#7]
Hi,

Cool that you have improved my url-to-image module, looks awesome. 

Anyways, I think we should join our efforts and maintain a one good tool instead of two separate ones. What do you think?

**Comment by cjpetrus** [comment]
@kimmobrunfeldt absolutely!  I actually had submitted a pr with  your repo just before you went on vacation ( I believe back in December ).  Didn't mean to leave out attribution :) 

Would love to join forces, what did you have in mind?

**Comment by kimmobrunfeldt** [comment]
Oh right, I totally forgot that. Sorry about that!
