### ISSUE TITLE
Incorrectly named fileQuality parameter

### ISSUE THREAD

**Issue by theted** [cjpetrus/url2img#8]
The `fileQuality` parameter (used in `oldOpts` when calling `page.render()` [in this line](https://github.com/cjpetrus/url2img/blob/master/src/url-to-image.js#L157)) is incorrectly named. I noticed that any value provided for the `fileQuality` parameter does not affect the quality or filesize of the output image. Renaming the parameter to `quality` instead of `fileQuality` (following the [PhantomJS documentation](http://phantomjs.org/api/webpage/method/render.html)) solves this issue.

**Comment by cjpetrus** [comment]
good catch!
